apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: exp-bluegreen
  namespace: demo
spec:
  replicas: 4
  strategy:
    blueGreen:
      activeService: exp-bg-active
      previewService: exp-bg-preview
      autoPromotionEnabled: true
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
          - templateName: prometheus-check
          - templateName: k6-check
        args:
          - name: service-name
            value: exp-bg-preview
          - name: target-url
            value: exp-bg-preview.demo.svc.cluster.local
          - name: vus
            value: "30"
  selector:
    matchLabels:
      app: exp-bluegreen
  template:
    metadata:
      labels:
        app: exp-bluegreen
        run-id: "1790200932"
    spec:
      containers:
        - name: app
          image: demo-app:v1
          env:
            - name: FAULT_MODE
              value: "errors"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: exp-bg-active
  namespace: demo
  labels:
    app: exp-bluegreen
spec:
  selector:
    app: exp-bluegreen
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: exp-bg-preview
  namespace: demo
  labels:
    app: exp-bluegreen
spec:
  selector:
    app: exp-bluegreen
  ports:
    - name: http
      port: 80
      targetPort: 8080